### ISSUE TITLE
"Name" disappeared in data harmonizer.

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#119]
It used to look like this

![Screen Shot 2023-03-02 at 7 08 46 PM](https://user-images.githubusercontent.com/44581429/222622077-09e06ea6-50c6-40c3-99b5-6fbaa556853a.png)

Now the info box looks like this

![Screen Shot 2023-03-02 at 7 08 27 PM](https://user-images.githubusercontent.com/44581429/222622116-0f5238ee-6d23-47d0-924a-499de56a80ed.png)

Where did name with the exact slot go?

**Comment by mslarae13** [comment]
Let's leave it out. Patrick will provide me a mapping

**Comment by pkalita-lbl** [comment]
This was taken out at the DataHarmonizer level in the work for https://github.com/microbiomedata/issues/issues/88. The rationale was that column names (as opposed to titles) are not really relevant to the general user. But @mslarae13 is not a general user 😁. She has valid reasons for wanting to know the column name _and_ title. I'm reopening this issue because it's pretty trivial to add a little Easter egg where you can get the column name by hovering over column title in the Column Help sidebar (_not the help popup!_ -- that's controlled by DataHarmonizer).
