### ISSUE TITLE
Script for converting submission portal metadata -> Mongo for postgres and data portal ingest

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#121]
James is working on a script to convert the metadata.

Issues with API permissions

**Comment by ssarrafan** [comment]
@mslarae13 is this for this sprint? this week?

**Comment by aclum** [comment]
@aclum @JamesTessmer  I'm sure Montana mentioned this but be sure to check https://github.com/microbiomedata/issues/issues/85 to make sure we don't duplicate records for samples that are in GOLD.

**Comment by ssarrafan** [comment]
I believe this is only for 1000 soils data.  Also I think this is in the process of being reviewed by @sujaypatil96. I'll move to the next sprint and change to in review status.  @JamesTessmer let me know if that's not accurate.

**Comment by ssarrafan** [comment]
@JamesTessmer who needs to review this for you?  Is there a PR?

**Comment by aclum** [comment]
@JamesTessmer  some feedback on the code based on viewing things in the data portal. It is recommended that for biosample_set collections that 'name' and 'description' are populated since those get displayed on the biosample pages on the data portal. It is convention in code Sujay has to populate 'type' both for biosample_set records and for study_set records so it would be nice if your code had the same behavior.

**Comment by ssarrafan** [comment]
@mslarae13 @aclum is it ok to close this issue?
