### ISSUE TITLE
8 of 10 studies are missing `gold_study_identifiers`

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/issues#153]
@naglepuff and I noticed recently as part of [this fix](https://github.com/microbiomedata/nmdc-server/pull/911) that all the older studies do not have the `gold_study_identifiers` slot populated. Currently we have a workaround where we parse the GOLD id out of the Study id where possible (since all the older studies have the `gold:` prefixed ids). So there is no immediate action required for all "open in GOLD" links to work, but we will eventually want to populate `gold_study_identifiers` for all studies, which will become essential when we move all ids to the `nmdc:` prefix.

**Comment by aclum** [comment]
gold_study_identifiers have been populated for 6 studies, the other two studies with gold identifiers as the study [id](url) had already been updated to also have gold_study_identifiers populated. One did not need updating, the other, Study id 
gold:Gs0110119, had an unresolvable gold_study_identifers value of GOLD:Gs0144557 which I removed and replaced with 
GOLD:Gs0110119.

This is fixed in mongo prod, ready for data portal ingest.

**Comment by ssarrafan** [comment]
Adding to backlog per Alicia

**Comment by naglepuff** [comment]
As of 8/18/2023, only 14 of 18 studies have `gold_study_identifiers` populated in production mongo. Do the remaining 4 have gold identifiers or is this expected?

**Comment by aclum** [comment]
@naglepuff this is expected. 

@ssarrafan depends what Mike/Jeff/Mary decide. They were going to talk through things and figure out what made sense to work through in terms of order [for the project board](https://github.com/orgs/microbiomedata/projects/80).

**Comment by mslarae13** [comment]
@aclum @naglepuff did this get finished? Is it on prod?

**Comment by aclum** [comment]
Not sure if the workaround got removed but the GOLD studies are populated if they exist.
