### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/issues#165]
https://docs.google.com/document/d/1Nm8hyI5usWLtRcPKR99XbZwuWLjueB8zSEUFzyUWr18/edit

**Comment by jkelliher-github** [comment]
@jkelliher-github @pkalita-lbl

**Comment by iockert** [comment]
Went through the web edits and made basic changes.

Discovered some blockers:

*It looks like there's no easy way to switch/drag elements from one template into another. This means that the Champion page and Event/News page will need to be rebuilt entirely. It looks like the Champion page can be rebuilt easily from the 'Builder' template, but it won't have the spotlight option. I'll try to have it match the look of the Ambassador page as much as possible. I also want to clean up the Champions slug as well, ideally to https://microbiomedata.org/champions/

*The news and events page will be trickier. There's no option for the Events' widget to be added to the Builder. I recommend using the 'Builder' Template for this, so that we will have flexibility in what we want do. But how should we do it? I'll sketch out an idea and show to Julia and Emiley.

**Comment by iockert** [comment]
Need to update Chris' picture and take off Natasha and add Kevin

**Comment by iockert** [comment]
Team page updated. Champion page in progress.

**Comment by iockert** [comment]
I have updated all the pages according to the update sheet.
