### ISSUE TITLE
Make sure consistent filtering for KO terms & M modules

### ISSUE THREAD

**Issue by emileyfadrosh** [microbiomedata/issues#167]
On the dev site, I am seeing inconsistencies in how functional search is returning results. For example, I would like to search for the KEGG module for nitrification (https://www.genome.jp/module/M00804). If I search M00804, this is what it returns: 
https://data-dev.microbiomedata.org/?q=ChwIABAAGAEiFCJLRUdHLk1PRFVMRTpNMDA4MDQi
<img width="1738" alt="Screen Shot 2023-03-30 at 1 12 50 PM" src="https://user-images.githubusercontent.com/76500011/228953474-5b72941a-2527-4bbd-80fe-8ea86b5c33cf.png">

As you can see, there is no filtering. 

However, looking at one of the individual KO terms, like [K00371](https://www.genome.jp/entry/K00371), does filter accordingly: 
https://data-dev.microbiomedata.org/?q=Ch8IABAAGAEiFyJLRUdHLk9SVEhPTE9HWTpLMDAzNzEi
<img width="1740" alt="Screen Shot 2023-03-30 at 1 15 45 PM" src="https://user-images.githubusercontent.com/76500011/228954082-00b45b6c-5e9f-4734-9cf4-c42766765c3b.png">

Same for another KO term: https://data-dev.microbiomedata.org/?q=Ch8IABAAGAEiFyJLRUdHLk9SVEhPTE9HWTpLMTA5NDQi

First, I would like to make sure that there are consistent results that are returned: so the Module would be a superset of all the KO terms. In this example case, it would be: K10944+K10945+K10946 K10535 K00370+K00371
[K10944](https://www.genome.jp/entry/K10944)+[K10945](https://www.genome.jp/entry/K10945)+[K10946](https://www.genome.jp/entry/K10946) [K10535](https://www.genome.jp/entry/K10535) [K00370](https://www.genome.jp/entry/K00370)+[K00371](https://www.genome.jp/entry/K00371)

Second, I am not sure why the Module filtering seems to be working in some cases and not in others. Using another module example, it seems to be working just fine (eg, https://www.genome.jp/module/M00165)! 
https://data-dev.microbiomedata.org/?q=ChwIABAAGAEiFCJLRUdHLk1PRFVMRTpNMDAxNjUi
<img width="1741" alt="Screen Shot 2023-03-30 at 1 24 29 PM" src="https://user-images.githubusercontent.com/76500011/228955886-990681c7-87a2-4095-9b21-5a07141a6193.png">

Ideally, both these should be fixed by GSP timeframe. I am not sure how long this will take to reach a solution, thanks for looking into this!

**Comment by jeffbaumes** [comment]
@emileyfadrosh it appears the mapping file from K-term to M-term we are using is incomplete. The mapping file does not seem to include any module number higher than M00786 even though there are many in the 800s and 900s. I will forward you the relevant thread from last year via email with the file we are using. Do we know how this was generated and can it be regenerated with the full set?

We are pulling in higher-number modules like M00804 into the text completion search which comes from a different file containing the module name, there are just no K terms associated with it. This problem seems to be manifesting as a complete match instead of an empty match as would be expected if there were no matching K terms to lookup in the annotation data, so even if we get the full matching data we should also fix the data portal bug of returning a full instead of empty match (@naglepuff FYI).

**Comment by aclum** [comment]
Emiley said in slack this looks good so we should be okay to close.
