### ISSUE TITLE
Metadata: Example row in the template

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#207]

**Comment by mslarae13** [comment]
Not sure we can do this? Or really need to? I think it'd be better to provide examples that people can download and look at.

Thoughts?

**Comment by pkalita-lbl** [comment]
Hmm not a lot of information to go off here. I think if we literally started people off with a row filled in for them we'd get a lot of submissions back with that row still in it. I agree there are probably better ways to guide people, so I'm in favor of closing this.

**Comment by ljohnson09** [comment]
I think downloading examples is an extra step that people shouldn't have to take (ideally we keep them in the SP interface as much as possible). Maybe a column help reconfiguration so that the example of the correct formatting is the first thing people see, then the additional information like definitions?

**Comment by mslarae13** [comment]
Do you mean a row?
Or do you mean restructure this box so the Example isn't the last thing listed? Was there a reason for wanting this change? Did the user research show people had trouble finding an example? I didn't get that from the sessions I sat in on. 
We have examples in the info box, which is where the definition is.

![Screenshot 2024-06-13 at 5 25 07 PM](https://github.com/microbiomedata/issues/assets/44581429/7018111f-fcbb-44f2-b592-e7d03a82d8c2)

**Comment by ljohnson09** [comment]
@mslarae13 Was the column help reformatted to remove the regex already? I thought we had discussed switching the order of the regex info with the Examples to make the example more obvious but now I am not seeing the regex in your screenshot. There were also missing examples that need to be filled out across the slots. The timeline on this particular ticket is also pre user research so maybe just what Patrick suggested above of closing it out since users in our round didn't seem to have an issue filling out the cells, more so learning how to format each slot w/ a valid term. Or if you can dig up where this bit of feedback came from we could compare to see if it was still an issue during our UR round.

**Comment by mslarae13** [comment]
We removed the regex, it's not really useful for most humans.
I agree we need to add more examples. I'll make a separate issue for this and link it.

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/mixs-6-2-release-candidate/issues/24
