### ISSUE TITLE
Create runtime / dagster scripts to handle generation of MetaG/MetaP aggregation collections

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#214]
- [x] MetaG  
- [x] MetaP
- [ ] Decide if we need to generate / model a schema object for these intermediate collections

**Comment by aclum** [comment]
we need to test metap but this is working for metag.

**Comment by ssarrafan** [comment]
@aclum @shreddd is this still something that needs to be done?  What's the priority?

**Comment by aclum** [comment]
Between Shane, Eric and I this work is complete. There are now scripts that run automatically in SPIN that run https://github.com/microbiomedata/nmdc-aggregator/blob/main/generate_functional_agg.py and https://github.com/microbiomedata/nmdc-aggregator/blob/main/generate_metap_agg.py which generate functional_aggregation_agg and metap_gene_function_aggregation respectively. A next step would be to create an API endpoint to submit this to mongo it is currently being added to mongo directly with pymongo. I will file a ticket for this because we need to eliminate direct access via pymongo in order to move to the cloud for increased stability over SPIN which is active work by Sanjay.

**Comment by aclum** [comment]
https://github.com/microbiomedata/nmdc-runtime/issues/611 is a request to have the json:submit endpoint support these aggregation records.
