### ISSUE TITLE
Rancher Workloads running under user mcovalt need to be fixed

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/issues#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A number of production/nmdc/* rancher workloads are deployed under user mcovalt (These are under Config -> Pod -> Labels and Annotations). 

The workloads should be cloned and redeployed under a current NMDC user since Matt is no longer with the project. Currently, if we remove Matt's access to the nmdcda user the workloads will fail.

### Expected Behavior

Workload should work under a current NMDC user. 

### Steps To Reproduce

The error occurs if `mcovalt` is removed from the nmdcda group in IRIS. 

### Environment

```markdown
OS: Rancher
```

**Comment by eecavanna** [comment]
**My plan:**
- [ ] 1. Familiarize myself with the Kubernetes resources in the "production" environment
    - So far, I've only familiarized myself with the ones in the new "development" environment. I think the environments are similar at a high level, but differ at the level of things like "which NERSC user a workload is running as".
- [ ] 2. Come up with a tentative plan for updating the user (i.e. the main point of this GitHub issue)
- [ ] 3. Run the tentative plan by @shreddd and the Kitware team

**Comment by eecavanna** [comment]
**Note:**

There are office hours for Spin every Friday. Source: https://www.nersc.gov/users/training/spin/#toc-anchor-2
> **Spin Office Hours**
> 
> All active Spin users are welcome to [make an appointment](https://nersc.as.me/?appointmentType=31827210) for hands-on help deploying or troubleshooting their apps in Spin. Appointments can currently be scheduled during Spin Office Hours every Friday 10:00a - 12:00p Pacific time. Sessions are held over Zoom. After scheduling, you will receive an email confirmation with further instructions.

**Comment by eecavanna** [comment]
As of right now, the workloads (on the `production` cluster on Spin) whose `nersc.gov/username` annotation says `mcovalt` are:

In the `nmdc` namespace: (6)

1. `backend`
2. `data`
3. `db`
4. `frontend`
5. `redis`
6. `worker`

In the `nmdc-dev` namespace: (0)

In other words, they are all in the production environment (i.e. `production` cluster and `nmdc` namespace) and are all part of the data portal stack (as opposed to the runtime stack).

**Comment by eecavanna** [comment]
> The workloads should be cloned and redeployed under a current NMDC user

I did an experiment (on the `development` cluster): I identified a deployment that had its `nersc.gov/username` annotation set to `mcovalt` (i.e. the `development/nmdc-dev/db` deployment), and I "redeployed" that deployment via the Rancher web UI. When it was back up and running, I confirmed the `nersc.gov/username` annotation _still_ said `mcovalt`. So, **redeployment, alone, wasn't sufficient to change that value.**

I think that's why @shreddd suggested the deployment be cloned. It is the new deployment (i.e. the result of the cloning operation) that would (presumably) reflect the current NMDC team member; i.e. whichever team member deploys it.

Since we would be cloning and deploying new copies of the current deployments, this is an opportunity to give the (new) deployments more descriptive names (e.g. `db` -> `portal-postgres`; see the `nmdc-dev` namespace for more examples). As a reminder, deployments access other deployments by using the names of the services that sit in front of the latter deployments; and services point to deployments by using selectors (on the service side) and labels (on the deployment side). So, all we'd have to update if the deployments were to be given different names, are the selectors that sit in front of those deployments.

**Comment by eecavanna** [comment]
I am actively working on this.

Here's what I've tried so far:
- Redeploying the deployments.
    - I redeployed the `worker` deployment via Rancher web UI.
    - **Result**: The original annotations persisted. 🔴 
- Editing the annotations via Rancher (regular web form).
    - I used the "Edit config" form to enter new values for the annotations, then I submitted the form.
    - **Result**: The original annotations persisted. 🔴 
- Editing the annotations via Rancher (YAML editor).
    - I used the "Edit YAML" form to enter new values for the annotations, then I submitted the form.
    - **Result**: The original annotations persisted. 🔴 
- Editing the annotations via `kubectl`.
    - I ran `$ kubectl --kubeconfig /path/to/kubeconfig.yml --namespace {namespace} annotate deployment {deployment_name} "{existing_key}={new_value}" --overwrite` to update the annotations of the `worker` deployment. I did this for all 4 annotations I wanted to update, all of which are `nersc.gov/*` annotations.
    - **Result**: The original annotations persisted. 🔴 

Note: According to [someone in the NERSC Users Slack workspace](https://nerscusers.slack.com/archives/C01LPA84AGM/p1694734514885879?thread_ts=1694730087.646829&cid=C01LPA84AGM), users can't edit the `nersc.gov/*` annotations.

I have opened a ticket with NERSC Support about this.

**Comment by shreddd** [comment]
Waiting on fix from NERSC

**Comment by ssarrafan** [comment]
Removing from sprint. Please add to current sprint when you have heard back from NERSC on fix. Thanks!

**Comment by eecavanna** [comment]
I heard back from NERSC on this on December 6, 2023. The issue on Spin has been fixed. I confirmed, today, that, when I redeploy a workload whose `nersc.gov/username` annotation shows someone else's username; once I redeploy it, it shows _my_ username.

**Comment by eecavanna** [comment]
This issue is fixed.

I confirmed that the `nersc.gov/username` annotation does not contain `mcovalt` on any of the workloads in the `nmdc` namespace. Here's the `kubectl` command I used to do that:

```shell
$ kubectl --kubeconfig ~/Downloads/spin.production.kubeconfig.yml \
  get deployments --namespace nmdc \
  -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.annotations.nersc\.gov/username}{"\n"}{end}' | grep mcovalt
```

Also, out of curiosity, I checked other types of resources, too. None of them had `mcovalt` as their `nersc.gov/username` value.

```shell
$ kubectl --kubeconfig ~/Downloads/spin.production.kubeconfig.yml \
  get pods,deployments,statefulsets,jobs,cronjobs --namespace nmdc \
  -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.annotations.nersc\.gov/username}{"\n"}{end}' | grep mcovalt
```
