### ISSUE TITLE
Determine lifecycle of nmdc minted ids and determine if they can be assigned within submission portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#4]
**Is your feature request related to a problem? Please describe.**
Need a process to see relationships between shoulders and classes

**Describe the solution you'd like**
Generate shoulders or document relationships between shoulders and classes

**Describe alternatives you've considered**
N/A

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

@mslarae13 can you fill out the following when it's time to work on this: 

Who will use this feature/enhancement? 
When will they use it?
How will they use it?
How will they test it to make sure it's working?
Is the request achievable? During one sprint? 
What is your definition of done for this request?

**Comment by mslarae13** [comment]
See https://github.com/microbiomedata/nmdc-schema/issues/369 (when complete) for what needs identifiers & shoulders.

**Comment by mslarae13** [comment]
From Donny on how the 'id' minter should be used 
"
yes, the current shoulder “mga0” was chosen to signal a “MetaGenomics Analysis (MGA)”activity and then because it’s a shoulder, it ends with a digit.

Here is what IDs should look like using my proposal of taking meaning out of shoulders and prefixing a shoulder with a type-code that can bear meaning:

nmdc:samp00q2z368
nmdc:stdy00q2z368
nmdc:mga00q2z368
nmdc:ompro00q2z368
nmdc:metap00q2z368
nmdc:nom00q2z368

I expect type codes to be all alphabetical characters, and compact - no more than six characters. That is, matching a regex of [a-z]{1,6}. Above I offer “samp” for sample, “stdy” for study, “mga” for “metagenomics analysis”, “ompro” for Omics Processing, etc., but this would not be up to me. The team would set the type codes and their correspondences, and we can add type codes over time.

There is only one shoulder above, 00 (double zero), and the blade (“key = shoulder + blade”), that is, the unique part under a given type-code-plus-shoulder namespace, is the same for each ID above, which is a base32 encoding of a 64-bit integer value plus a checksum (same as current scheme), which helps defend against many communication errors.

It is critical that an ID analyzer can decompose any structure without lookup. In the proposed scheme, an analyzer can always get the type code by grabbing letters after “nmdc:” until it hits a digit. Then it can always get the shoulder by starting with that digit, collecting zero or more letters, and finishing when it hits a second digit. The rest is the blade. In the previous (currently deployed) scheme, a shoulder doesn’t start with a digit because there’s no preceding type code that needs to be distinguished when parsing an ID.

We could technically go far with just one shoulder if everyone agrees to use the one central minting service. But shoulders are (1) essential for distributed minting with conflict-free merging, like if EMSL wants to install an offline minter with a local database that ensures locally unique blades, NMDC can just assign the minting steward a shoulder; and (2) shoulders ensures unlimited IDs  when storing blades as 64-bit integers for efficiency. It’s unlikely to be a practical problem, as a 12-character base32-encoded string  can represent 2^60 ~ 1e18 integers, but shoulders provide convenient compact and opaque (no semantics) namespacing within the broader NMDC ID namespace for whatever reason we may find that convenient — using legacy IDs as blades, keeping total ID lengths compact even if large volumes are minted (perhaps not all minted IDs will ultimately be shared broadly), etc., although the motivating use case is again to accommodate distributed minting by known organizations/sites in case a central minting server is not continuously available (a standard code+database container can be maintained for would-be minting organizations to use).

This actually reminds me a bit of the DOI system. DOIs all begin with “10.”  And then organizations get assigned a full prefix, like “10.1038”. You could think of “10.” as analogous to “nmdc:” and “1038/“ as analogous to a shoulder. And so you have a DOI like “10.1038/s41597-019-0184-5”.

"

**Comment by turbomam** [comment]
Where can we see what shoulder is appropriate for identifying instances of the various classes?

`id` for all classes will use an NMDC minted ID, but we should specify the shoulder in the `pattern` `slot_usage`

**Comment by turbomam** [comment]
Clarification needed: is the blade portion of an nmdc minted identifier random, or is it based on some input?

**Comment by pkalita-lbl** [comment]
> is the blade portion of an nmdc minted identifier random, or is it based on some input?

Random

**Comment by turbomam** [comment]
I updated the name of this issue to make it more concrete.

I know how to assign nmdc minted identifiers to studies and biosamples in off0line batch opertations.

Let's **determine the earliest point in time that they could be assigned** to instances of those two classes, when the input is coming from the submission portal

And let's determine how to look up the **provenance** of an nmdc minted identifier: when was it created? what agent created it? Is there a way to capture the intended use at creation time?
- queries like this should support either full identifier input or just the shoulder

I don't want our ability to look up nmdc minted identifiers to be limited to APIs that look in MongoDB "*_set" collections

**Comment by pkalita-lbl** [comment]
I wouldn't consider this gospel truth but according to my understanding:

> Let's determine the earliest point in time that they could be assigned to instances of those two classes, when the input is coming from the submission portal

I did some quick hack-y prototyping to verify that it is possible to make a request to the ID minter when at least once cell of a row is entered in DataHarmonizer and then to place the result into a column that is not user-editable. I'm sure there are plenty of usability details to account for, but I'd say it's technically feasible to mint IDs that early if that's what makes sense to do.

> let's determine how to look up the provenance of an nmdc minted identifier: when was it created? what agent created it? Is there a way to capture the intended use at creation time?

The "when" and "what agent" are available via the `/ids/bindings/{id}` endpoint. For example: https://api.dev.microbiomedata.org/ids/bindings/nmdc:fk0frj045. I suppose the `what` field may be for capturing the intended use? That might need a little clarification from @dwinston 

> queries like this should support either full identifier input or just the shoulder

I think only full identifiers are supported at the moment

**Comment by pkalita-lbl** [comment]
After discussing this issue with @mslarae13 we're setting the following as the completion criteria for this issue:

1. Determine which types of entities need NMDC-minted identifiers.
2. Decide on identifier type codes (a string of "alphabetical characters... no more than six characters" as outlined by @dwinston above) for each type of entity.
3. Ensure those type codes are available in the NMDC Runtime ID minter.
4. Document the type codes; integrate in schema as needed.

**Comment by pkalita-lbl** [comment]
Updates to above questions

1. I think all we can say with certainty right now is: studies and biosamples. With regard to anything involving workflows is still in flux while this [proposal](https://docs.google.com/presentation/d/1Kh43lFyHBJX5RiV_dJun3DyjHdUE_Q97rhX2WEZJ9Lw/edit#slide=id.p) is being discussed.
2. @dwinston has a proposal [here](https://github.com/microbiomedata/nmdc-schema/issues/369#issuecomment-1256541677) which seems good to me.
3. As far as I can tell nmdc-runtime implements a simpler `nmdc:<shoulder><blade>` and not (yet) the `nmdc:<type-code><shoulder><blade>` ID format detailed above. I'm not totally sure what the roadmap for implementing the new format is, but I think that needs to happen first.
4. We could add something now to the schema for studies and biosamples based on the current proposals.
