### ISSUE TITLE
Outage Page for NMDC

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/issues#441]
We need an outage page for when NMDC services on Spin are unavailable

This could be done by creating a page on github.io and proxying the Cloudflare data portal or other user facing services to this.

It should 
1. Describe the outage and duration (see NERSC motd for details).
2. Offer users the option of using the backup instance at EMSL for the data portal. 

Run the text by Emiley / Shreyas / Alicia for confirmation.

Once ready we can point cloudflare to this page via proxy.

**Comment by eecavanna** [comment]
I created a repository on GitHub for this: 
https://github.com/microbiomedata/nmdc-outage-website

The `main` branch gets automatically deployed to GitHub Pages, here: 
https://microbiomedata.github.io/nmdc-outage-website/

I implemented a preliminary version of the outage page, which you can see at the second URL above.

**Comment by eecavanna** [comment]
I made it so the text on the page (other than the "We'll be right back" heading) is defined in a Markdown file. I think that'll make it easier for people who are familiar with Markdown, but not HTML, to edit the message over time.

**Comment by shreddd** [comment]
Could you also add the following text: "Please note that submission portal metadata may not be persistent on the backup instance".

**Comment by eecavanna** [comment]
I'll close this issue since the outage page has been implemented (although Cloudflare is not pointing at it yet).

Subsequent issues can be created in the outage page's repo, at: https://github.com/microbiomedata/nmdc-outage-website

For example, I'll create an issue in the outage page's repo, about mapping the data portal and runtime URLs to the outage page when the outage begins.
