### ISSUE TITLE
Milestone - Integration plan for SeqCode taxonomy in reference database (2.21) DUE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#458]
Reference database augmentation
Easy to access and well curated reference databases empower open-source research and help scale the
impact of microbiome research. NMDC will partner with the SeqCode Initiative (see Letter of Support) to
expand the current list of bacterial and archaeal taxa by incorporating data inferred by genome sequences
and providing new taxonomic names to microbes that have yet to be cultured but whose genomes have
been interrogated. To provide more taxonomic context for microbiomes under study, and to support
broad community adoption of the SeqCode taxonomy and nomenclature system, the NMDC will work
directly with the SeqCode development team to outline a plan to update our sequence-based reference
genome and taxonomy databases (Milestone 2.21).

Page 34

**Comment by emileyfadrosh** [comment]
Will be meeting with SeqCode Registry & Nomenclature WG on Wednesday, 1/31. Have this topic as an agenda item and will hopefully have a plan moving forward.

**Comment by ssarrafan** [comment]
> Will be meeting with SeqCode Registry & Nomenclature WG on Wednesday, 1/31. Have this topic as an agenda item and will hopefully have a plan moving forward.

@emileyfadrosh any update on this milestone?  Are you expecting this to be done by the end of March?

**Comment by emileyfadrosh** [comment]
Sorry for the slow update here. The working group met on 1/31 to discuss a range of topics related to the registry development and next steps. Unfortunately there still is no dedicated funding to this effort. The registry has a basic portal here: https://disc-genomics.uibk.ac.at/seqcode, and code here: https://github.com/seq-code/registry. We discussed how NMDC could connect. While there is a basic API, documentation is not available as of yet. Instead, it was confirmed that the GTDB is able to sync with the SeqCode registry and any updates to GTDB would include latest taxonomy. Since JGI uses GTDB for taxonomic assignments for MAGs, we can keep aligned with the updated taxonomy through the binning pipeline. 

We will stay involved in the WG to see whether they are able to secure stable funding, and reassess our strategy if there is a future path to connect directly.
