### ISSUE TITLE
Workflow automation end-to-end testing

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#60]
One of the dependencies for GSP data in portal. Related to #37 

@aclum @scanon

**Comment by scanon** [comment]
Using the runtime changes and the prototype scheduler, I have been able to run through the entire end-to-end workflow for metagenomes.  Converting the prototype scheduler into a dagster job is in progress.  We can retest once that is ready.  However, we could use the prototype scheduler to process data if we are in a crunch.

**Comment by scanon** [comment]
My next steps are to start looking through the output from the test runs for any flaws.  I could use @aclum help on this part.

**Comment by scanon** [comment]
From @aclum 

- [ ] Issue 1: git_url is still incorrectly hard coded to the annotation repo for mgrqc, version is also incorrect and there is not a new tagged version. perhaps we don't need a new tagged version but we at least need a tag name that is valid for the correct repo /global/cfs/cdirs/m3408/ficus/pipeline_products/gold:Gp0000000/nmdc:mgrqc0xxxx.1/objects.json
- [] issue 2: there is no git_url in the objects.json for assembly so looks like this isn't getting passed correctly (edited) 
- [] Issue 3: incorrectly named annotation info file
/global/cfs/cdirs/m3408/ficus/pipeline_products/gold:Gp0000000/nmdc:mgann0xxxx.1/scaffold_imgap.info should be named the same as the other files with the nmdc identifier (edited) 
-[] issue 4: annotation is missing a lot of the intermediate files, check with Michal here. Looks to me like we are missing the updates to finish_ano needed to capture those files (edited) 
- [] issue 5: contig names did not propagate correctly to binning results. Contig headers look like actid_scf_2049_c1 instead of having the contig names from the output of assembly (ie nmdc:mgasm0xxxx.1_scf_1_c1). This incorrect naming propagates to a number of files like the objects.json and MAGs_stats.tsv (edited)

**Comment by ssarrafan** [comment]
This looks like it's still in progress. Moving to the next sprint. @scanon let me know if you're not planning to work on this the next few weeks.

**Comment by ssarrafan** [comment]
Assuming this testing is still in progress. Please add an update if this is done or needs to move to the backlog @aclum @scanon

**Comment by aclum** [comment]
@scanon Can this be closed? We are running real datasets now.

**Comment by ssarrafan** [comment]
I'm going to close this based on Alicia's comment.  @scanon let us know if it should be re-opened.
