### ISSUE TITLE
Design validation for IDs 

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#7]
**Is your feature request related to a problem? Please describe.**
Trying to make sure identifiers are accurate and in the right slots

**Describe the solution you'd like**
Design a way to validate and verify that correct IDs are used in their designated alternate identifiers slots 

**Describe alternatives you've considered**
Will be part of design

**Acceptance Criteria**
Create a checklist or scenario-based acceptance criteria, from the users perspective, that answers the following: 

Who will use this feature/enhancement? Team will use to make sure identifiers are accurate
When will they use it? As needed
How will they use it? Mark can you add something here?
How will they test it to make sure it's working? Mark can you add something here?
Is the request achievable? During one sprint? Design only for one sprint
What is your definition of done for this request? That there is a design for how to do the verification and validation of identifiers in designated slots

**Comment by turbomam** [comment]
Thanks for the thorough issue, @ssarrafan 

I'm confused by several parts of it, but the Acceptance Criterial will be a good start.

The schema **is** the validation. If stakeholders can provide expected-to-pass identifier values and expected-to-fail values, we can check those with the JSON schema.

Ie, no further design is required. Just example values.

**Comment by turbomam** [comment]
What does it mean for the identifier to go in the right slot? Identifiers usually are modeled **as slots**.

How will we know if it is accurate?

Does this only apply to alternative identifiers?

**Comment by ssarrafan** [comment]
@turbomam should this issue be re-worded or closed?

**Comment by ssarrafan** [comment]
In the future provide examples of correct and incorrect or a regular expression of how IDs should be formatted for slots.  Need to figure out who can provide the information before proceeding.

**Comment by ssarrafan** [comment]
Discussed at squad meeting 10/5 and moving to backlog.

**Comment by turbomam** [comment]
@ssarrafan If this issue is to move forward, we will need examples of valid and invalid values for each identifier slot. Once those are provided, patterns can be applied to each of the slots so that invalid identifiers will fail during the validation stage of a script like https://github.com/microbiomedata/nmdc-schema/blob/issue-486-data-to-7-0/util/migrate_7.py

Definition of completion: stakeholder have provided valid and invalid examples. The script linked above passes all valid identifiers. The invalid identifiers are loaded as examples in https://github.com/microbiomedata/nmdc-schema/blob/main/test/data/invalid_schemas, so they will be tested each time `make test` is run

**Comment by ssarrafan** [comment]
@turbomam I think I'll close this issue because I can't recall who asked me to create it back in August. I will have to remember to put in this information in the future. Thanks.
