### ISSUE TITLE
Add metrics report for submission portal sandbox

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#742]
Currently, the NMDC submission portal sandbox is wiped every sunday. We use this for workshops. It would be good to get a count of # of submissions made to this sandbox site before each clearing. 

This metric is something we could report as # of users that are experimenting with NMDC or for # of workshop attendees.

FYI
@jkelliher-github @ljohnson09 @pkalita-lbl

**Comment by mslarae13** [comment]
To unblock: need to discuss priority level & determine level of effort

**Comment by eecavanna** [comment]
### About some related work

There is a ticket about implementing an admin-only API endpoint that returns information about all submissions that exist in the database.

https://github.com/microbiomedata/nmdc-server/issues/1285

There is a draft PR associated with the ticket. In the PR (i.e. the PR branch), that API endpoint has been implemented, but no tests have been implemented that target it yet.

https://github.com/microbiomedata/nmdc-server/pull/1290

That endpoint returns a TSV file. This is to facilitate quarterly metrics gathering for reports, where a team member manually reviews submissions to identify new ones, fake/test ones, etc.

Most of the code underlying that API endpoint could be reused for an API endpoint that returns the total number of submissions. Such an endpoint could be registered with the https://github.com/microbiomedata/nmdc-metrics-fetcher that runs every night and then we would have nightly records of that number.

### Some thoughts on interpreting a raw "number of submissions" number

1. I think the engagement team may have more reliable/direct ways of determining the number of attendees of a workshop (e.g. checking a roll sheet/registrant list).
2. The number of submissions may not be the same as "the number of users that are experimenting with NMDC." People may require more information from the API endpoint in order to determine the latter (e.g. number of unique ORCIDs).

**Comment by mslarae13** [comment]
To discuss and confirm with the group, -sandbox may go away. See https://github.com/microbiomedata/issues/discussions/743

**Comment by mslarae13** [comment]
We've decided the sandbox is going to go away.. so no point in adding functionality to it!
