### ISSUE TITLE
Add “delete this submission” button to NMDC submission portal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#826]
Allow anyone with contributor roles (PI or submitter) to delete a submission

Allow NMDC admins to delete a submission.
- I expect people will forget about their test/ workshop submissions & to avoid excessive clogging of the submission portal I'd like to be able to delete a submission

Suggestion
![Screenshot 2024-08-15 at 10 34 14 AM](https://github.com/user-attachments/assets/41c7e1f2-5de6-4398-a748-05e4e96000b5)

![Screenshot 2024-08-15 at 10 25 03 AM copy](https://github.com/user-attachments/assets/ab2923bd-88eb-4076-9367-b283c59160ab)

i = Deleting a submission will eliminate it from the database. There is no way to re-instate a deleted submission.

**Comment by pkalita-lbl** [comment]
Some UI notes:

* I think in the past we talked about adding an "overflow menu" to each row in the submission table. So, to the right of the "Resume" button add a new button with a [three dot icon](https://fonts.google.com/icons?selected=Material+Icons:more_vert:&icon.query=more_vert&icon.size=24&icon.color=%23e8eaed). Clicking that button should open a [menu](https://v2.vuetifyjs.com/en/components/menus/). For now that menu will just have a single list item, "Delete". In the future we could expand that menu for other actions like copying a submission, etc.
* I don't know if we need the info `i` icon suggested by the above sketches. Since the "Delete" button will just open a modal with an explanation of the consequences I think we can just have all the necessary information in the modal.
* I think the modal concept in the sketches looks generally fine. We can iterate on the exact wording if needed. Check out the [`v-dialog`](https://v2.vuetifyjs.com/en/components/dialogs/) Vuetify component. We might want to consider using the `persistent` option to ensure that the user proactively chooses to either delete or not delete the submission. Otherwise I would generally adhere to the examples in the Vuetify docs and other usages of `v-dialog` in the `nmdc-server` codebase to ensure consistency.

**Comment by mslarae13** [comment]
> Clicking that button should open a [menu](https://v2.vuetifyjs.com/en/components/menus/). For now that menu will just have a single list item, "Delete". In the future we could expand that menu for other actions like copying a submission, etc.

Yes please. So there's no accidental deletions :)
I look forward to adding a download sample metadata button :)

**Comment by mslarae13** [comment]
> I don't know if we need the info i icon suggested by the above sketches. Since the "Delete" button will just open a modal with an explanation of the consequences I think we can just have all the necessary information in the modal.

Fair.

**Comment by mslarae13** [comment]
Note I forgot, don't allow deleting of "Submitted" submissions. 
So only in progress submissions can be deleted.

**Comment by mslarae13** [comment]
@pkalita-lbl can you add an issue for "soft" delete

**Comment by pkalita-lbl** [comment]
> @pkalita-lbl can you add an issue for "soft" delete

Here it is: https://github.com/microbiomedata/nmdc-server/issues/1440

**Comment by JamesTessmer** [comment]
@mslarae13 the PR for this issue has been merged in.

**Comment by mslarae13** [comment]
Tested via the API submission summary endpoint. I delete a submission and it was in fact deleted! Good work James!
