### ISSUE TITLE
Populate `Manifest` records for proteomics samples

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/issues#948]
Now that the [`Manifest`](https://github.com/microbiomedata/nmdc-schema/blob/2955691414b0b5144407e66ee6e53c697a134d94/src/schema/nmdc.yaml#L258) class exists in the schema, we need to populate `Manifest` records for proteomics samples that should be associated with one another (run in the same experiment, etc.)

https://github.com/microbiomedata/nmdc_notebooks/issues/95 is dependent on these records being populated.

**Comment by samobermiller** [comment]
The 52 proteomic processing records have two different `associated_studies`. Within each of the`associated_studies`, the sample start dates are sequential. I created two different manifest_sets in [manifest_sets.json](https://drive.google.com/file/d/1907L2zMBNbJRPQx5RF8Gb-0nrCtLVHEb/view?usp=drive_link) and created a [change sheet](https://drive.google.com/file/d/1LSp7nnS0gksVtpxLPSIQUOii6mTz0no4/view?usp=drive_link) to update the in_manifest slot of the processed data objects associated with these proteomic samples. There are 208 processed data object IDs (52 processing records x 4 different outputs from proteomics workflow). Both the json and the change sheet passed the API validations. @bmeluch could you load these to dev and prod for me since you have permissions?

**Comment by bmeluch** [comment]
Done!

**Comment by aclum** [comment]
There are some malformed records in dev. Was there testing with queries:run earlier or these were only updated via changesheets? Just trying to figure out if we have an issue with the changesheet validation process or in some other area. queries:run did not previously have validation but it does now. cc @eecavanna

**Comment by aclum** [comment]
this appears to be an issue with changesheets validate.

**Comment by bmeluch** [comment]
@aclum by malformed records do you mean the ones with extra brackets and quotes? These were all done via changesheet and I removed the quotes/brackets before submitting them to prod. But I wasn't sure how to fix the ones in dev

**Comment by aclum** [comment]
yes, the records with extra brackets/quotes causes a problem for nmdc_automation which uses some other linkml tools. In the future you can use changesheets delete or a queries:run update command to fix these but Eric has done that already.

**Comment by ssarrafan** [comment]
So can this issue be closed then?  @aclum @samobermiller

**Comment by aclum** [comment]
For record keeping the 'malformed' record issue in dev was determined to be because of a missing structured syntax pattern for Manifest id mentions.
